from models.landpage.__base import *
from models.landpage.hero import *
from models.landpage.about import *
from models.landpage.contact import *
from models.landpage.experiences import *
from models.landpage.footer import *
from models.landpage.landpage import *
from models.landpage.projects import *
from models.landpage.skills import *
