version: '3.8'

services:
  api:
    build:
      context: ./portfolio-api
      dockerfile: Dockerfile
    env_file:
      - ./portfolio-api/.env
      - ../.env
    ports:
      - "8000:8000"
    restart: always
